### ISSUE TITLE
404 response when using voucher when "can_only_send_to_me": False

### ISSUE THREAD

**Issue by rdenham** [WEHI-ResearchComputing/FileSenderCli#14] opened 2024-01-11 03:52 UTC
I wanted to be able to send a voucher to a guest, but allow them to send a file to any recipient. I modified the lines in `main.py` to look like:

```python
    result = client.create_guest({
        "from": username,
        "recipient": recipient,
        "options": {
            "guest": {
                "valid_only_one_time": True,
                "can_only_send_to_me": False,
            }
        }
    })
```

This works fine, except when the guest uses the voucher from the web interface, file gets sent fine, but as soon as it is sent, the page you are on returns a 404 response, with a 'Page Not Found; The page you have attempted to reach is not available, please check your spelling and try again, or return to the home page' message.

I guess that is because as soon as it is sent, the voucher expires, and the page is no longer valid. 

So no loss in functionality, just might cause some confusion to the guest when they use the voucher.

I wonder if you had any suggestions on how to avoid this minor issue?

**Comment by multimeric** [comment] 2024-01-11 05:40
Okay so there are sort of two issues here. The first is that the CLI doesn't support configuring the guest options, which I've now addressed in #15.

I've now also looked into the second issue. It seemed to be caused by the fact that I was defining some of the options wrongly in the JSON request, which caused FileSender to generate a malformed redirect URL. Can you please try installing the branch (`pip install git+https://github.com/WEHI-ResearchComputing/FileSenderCli.git@guest-options`), and then run your guest creation using `filesender invite <OTHER OPTIONS> --no-only-to-me` to verify that this is now fixed?

**Comment by rdenham** [comment] 2024-01-12 00:04
Thanks @multimeric for implementing the guest options, thats great!

I did test, and now I can send a voucher allowing the recipient to send a file to any address.

The problem that I have now is it seems to me that the options don't actually work, so 

```
filesender invite robert.denham@des.qld.gov.au 
```

and 

```
filesender invite robert.denham@des.qld.gov.au --no-only-to-me
```

and

```
filesender invite robert.denham@des.qld.gov.au --only-to-me
```

have the same result. The recipient is able to send to any address in all cases. I also tested `--one-time` and it doesn't seem to make a difference either. Recipient is able to reuse the voucher with and without this option.

**Comment by rdenham** [comment] 2024-01-12 00:08
managed to work out the verbose option!

I get this:

```
filesender invite robert.denham@des.qld.gov.au --only-to-me --one-time True
{
    'id': xxx,
    'userid': xxx,
    'user_email': 'robert.denham@xxx',
    'email': 'robert.denham@xxx',
    'token': 'xxxx',
    'transfer_count': 0,
    'subject': None,
    'message': None,
    'options': [],
    'transfer_options': {'get_a_link': False},
    'created': {'raw': 1705018012, 'formatted': '12/01/2024'},
    'expires': {'raw': '1706746012', 'formatted': '01/02/2024'},
    'upload_url': 'https://filesender.aarnet.edu.au/?s=upload&vid=2f560e22-85ad-4097-ae3b-2b9c8c59d1b9',
    'expiry_date_extension': 0,
    'errors': []
}
Invitation successfully sent
```

I don't think those options are coming through.

**Comment by rdenham** [comment] 2024-01-12 01:19
Looking at your main branch, I suspect main should be something more like:

```python
    guest_options = {"valid_only_one_time": one_time,
                    "can_only_send_to_me": only_to_me,
                    "email_upload_started": email_upload_started,
                    "email_upload_page_access": email_page_access,
                    "email_guest_created": email_guest_created,
                    "email_guest_created_receipt": email_receipt,
                    "email_guest_expired": email_guest_expired}

    result = client.create_guest({
        "from": username,
        "recipient": recipient,
        "options": {'guest':guest_options}
        }
    )
```

Which would produce:

```sh
{
    'id': 290586,
    'userid': 68148,
    'user_email': 'robert.denham@xxx',
    'email': 'robert.denham@xxx',
    'token': 'xxx',
    'transfer_count': 0,
    'subject': None,
    'message': None,
    'options': {'email_upload_started': False, 'email_upload_page_access': False, 'valid_only_one_time': True, 'can_only_send_to_me': True, 'email_guest_created': True, 'email_guest_created_receipt': True, 'email_guest_expired': False},
    'transfer_options': {'get_a_link': False},
    'created': {'raw': 1705022304, 'formatted': '12/01/2024'},
    'expires': {'raw': '1706750304', 'formatted': '01/02/2024'},
    'upload_url': 'https://filesender.aarnet.edu.au/?xxx',
    'expiry_date_extension': 0,
    'errors': []
}
Invitation successfully sent
```

**Comment by multimeric** [comment] 2024-01-12 01:59
Indeed, I initially thought that my request structure was wrong (https://github.com/filesender/filesender/issues/1772), but it was rather an obscure FileSender bug (https://github.com/filesender/filesender/issues/1773). I've now reverted the change so guest options will now work again, added a workaround for the FileSender bug that broke the redirects, and fixed the verbose flag (which was supposed to be a flag and not an argument, like the rest of the subcommands). Can you please test your use case again?

**Comment by rdenham** [comment] 2024-01-12 02:07
great. I tested:

```sh
filesender  invite robert.denham@des.qld.gov.au --verbose
filesender  invite robert.denham@des.qld.gov.au --no-only-to-me --verbose
filesender  invite robert.denham@des.qld.gov.au --no-only-to-me --no-one-time --verbose
```

all these worked as expected. Thanks for your work on this, it will be useful to our group.

**Comment by multimeric** [comment] 2024-01-12 02:10
Great! Thanks for your helpful bug report as well

**Closed** 2024-01-12 02:10 UTC
